version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_AWS_REGION=${VITE_AWS_REGION}
      - VITE_AURORA_ARN=${VITE_AURORA_ARN}
      - VITE_AURORA_SECRET_ARN=${VITE_AURORA_SECRET_ARN}
      - VITE_AURORA_DATABASE=${VITE_AURORA_DATABASE}
      - VITE_OPENAI_API_KEY=${VITE_OPENAI_API_KEY}
      - VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
      - VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN}
      - VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
      - VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET}
      - VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID}
      - VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}